traefik:
  ports:
    traefik:
      port: 9000
      exposedPort: 9000
      protocol: TCP
    web:
      expose:
        default: true
      redirectTo:
        port: websecure
    websecure:
      expose:
        default: true
  api:
    dashboard: true
    insecure: true

  additionalArguments:
    - "--api.insecure=true"
    - "--api.dashboard=true"

  ingressDashBoard:
    enabled: true
  
  persistence:
    enabled: false

  service:
    type: LoadBalancer