traefik:
  ports:
    traefik:
      port: 9000
      exposedPort: 9000
      protocol: TCP
    web:
      expose:
        default: true
      redirectTo:
        port: websecure
    websecure:
      expose:
        default: true
  api:
    dashboard: true

  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.czgeeklab.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      entryPoints:
        - websecure
      tls: {}
  
  persistence:
    enabled: false

  service:
    type: LoadBalancer
