apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  addresses:
    - 192.168.10.50-192.168.10.60
