apiVersion: v2
name: argocd-self-managed
description: Self-managed ArgoCD configuration
type: application
version: 1.0.0
appVersion: "2.13.0"

dependencies:
  - name: argo-cd
    version: "7.7.0"
    repository: "https://argoproj.github.io/argo-helm"