apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token-secret
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-tunnel-token-secret
  data:
    - secretKey: tunnel-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/cloudflare
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: cloudflare-tunnel-token