apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps-waves
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - appName
        generators:
          - git:
              repoURL: 'https://github.com/TomBejHome/proxmox-homelab.git'
              revision: HEAD
              files:
                - path: "kubernetes/apps/*/config.json"
          - list:
              elements:
                - appName: metallb
                  ignoreDiff:
                    - group: admissionregistration.k8s.io
                      kind: ValidatingWebhookConfiguration
                      name: metallb-webhook-configuration
                      jsonPointers: ["/webhooks/0/clientConfig/caBundle"]
                    - group: admissionregistration.k8s.io
                      kind: MutatingWebhookConfiguration
                      name: metallb-webhook-configuration
                      jsonPointers: ["/webhooks/0/clientConfig/caBundle"]
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/TomBejHome/proxmox-homelab.git'
        targetRevision: HEAD
        path: '{{path}}/chart'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      
      ignoreDifferences: '{{ignoreDiff}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true